name: minizfvr
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - pyqt=5
  - pyqtgraph=0.13.7
  - numpy>2.0
  - scipy>1.13
  - numba
  - matplotlib
  - pip:
      - h5py
      - qdarkstyle
      - qimage2ndarray