name: minizfvr
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - numpy<2
      - scipy
      - matplotlib
      - PyQt5
      - pyqtgraph
      - h5py
      - qdarkstyle
      - qimage2ndarray
      - moderngl
      - opencv-python
      - pyzmq